CREATE TABLE users(
	id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	name VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(100) NOT NULL,
	role VARCHAR(20) NOT NULL CHECK(role IN ('SALLER','BUYER')),
	created_at TIMESTAMP,
	updated_at TIMESTAMP
);